services:
  yarp:
    image: brunomartens/yarp:latest
    ports:
      - 80:8080
      - 443:8081
    networks:
      - brunomartens
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    # volumes:
    #   - ./https:/https
  api:
    image: brunomartens/api:latest
    networks:
      - brunomartens
  portal:
    image: brunomartens/portal:latest
    networks:
      - brunomartens

networks:
  brunomartens:
    driver: bridge